### ISSUE TITLE
Aborting and resuming the download script

### ISSUE THREAD

**Issue by 1kastner** [bioidiap/bob.db.voxforge#4]
The download and untar script checks whether a directory already exists and in that case it skips it. So generally speaking the script is capable of being aborted and resumed at a later point. Only one problem exists: if you start to download the same file the second time, wget adds ".[number]" at the end of the file, so "file.tgz.1" for the second attempt and so on. That means, the script in its current implementation processes the first download attempt and hence the broken file.
One fix which is customized for my personal needs can be found at https://gist.github.com/1kastner/46a6e8510c47901cb55d - I am not that well in shell scripting. It should take the file name "name.tgz.[HIGHEST_NUMBER]" instead of the first download attempt.
I hope I could make my point clear.

**Comment by siebenkopf** [comment]
I think it would be easier to go to the according download directory and delete the incomplete file before restarting the script. There is no need to keep the broken file anyways. 

Hence, in my eyes no need to adapt the script as a simpler (manual) solution can be found.

**Comment by 1kastner** [comment]
Well, because of the bad internet connection I had 40 damaged archive
files which is quite a lot for manual deleting. But that might really be
an extreme case.

Am 29.12.2015 um 17:57 schrieb Manuel Günther:
